#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/tmp/code-server/lib/code-server-4.123.0/lib/node" "/home/JaganathVinodKumar/.local/share/code-server/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"